[project]
name = "blackvuesync"
version = "2.0a"
description = "Synchronize recordings from BlackVue dashcams to a local directory"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
keywords = ["blackvue", "dashcam", "sync", "backup"]

dependencies = []

[project.optional-dependencies]
# development dependencies
dev = [
    "black~=25.11",
    "Flask~=3.1",
    "pytest~=8.4",
]

[project.urls]
Homepage = "https://github.com/acolomba/blackvuesync"
Repository = "https://github.com/acolomba/blackvuesync"
Issues = "https://github.com/acolomba/blackvuesync/issues"

[build-system]
requires = ["setuptools>=58.0.4"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py39"]
